In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [71]:
text = ['the glass of milk',
       'the glass of water',
       'I prefer coffee than tea',
       'I love travelling from one place to another',
       'I love machone learning specially data science']

text

['the glass of milk',
 'the glass of water',
 'I prefer coffee than tea',
 'I love travelling from one place to another',
 'I love machone learning specially data science']

# Using One_Hot

In [72]:
voc_size=100
one_hot_repre = [one_hot(words, voc_size) for words in text]
one_hot_repre

[[23, 14, 43, 42],
 [23, 14, 43, 41],
 [51, 99, 68, 32, 71],
 [51, 4, 40, 51, 96, 67, 27, 12],
 [51, 4, 46, 33, 34, 76, 10]]

# Using Embedding

In [73]:
padding_sequence = pad_sequences(one_hot_repre, padding='post', maxlen=10)
print(padding_sequence)

[[23 14 43 42  0  0  0  0  0  0]
 [23 14 43 41  0  0  0  0  0  0]
 [51 99 68 32 71  0  0  0  0  0]
 [51  4 40 51 96 67 27 12  0  0]
 [51  4 46 33 34 76 10  0  0  0]]


In [74]:
model = Sequential()
model.add(Embedding(100, 8, input_length=10))

#100 for number of distinct word or vocabulary size
#8 for size of the embedding vector
#input_length=10 referes the size of each input sequence.

In [75]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 10, 8)             800       
Total params: 800
Trainable params: 800
Non-trainable params: 0
_________________________________________________________________


In [76]:
model.compile(loss='mse',
             optimizers='adam',
             metrics=['accuracy'])

In [77]:
model.predict(padding_sequence)

array([[[ 0.04881623, -0.04362694, -0.0319032 ,  0.00446813,
         -0.00040964,  0.02457441, -0.03153659,  0.00950763],
        [-0.04011356, -0.0122643 ,  0.0352467 , -0.04523439,
         -0.01831709,  0.00068257,  0.02801796,  0.00040097],
        [-0.03414035, -0.00874329, -0.02835494,  0.028915  ,
         -0.02792256,  0.0035617 , -0.04794943, -0.0497116 ],
        [-0.03293373, -0.00689679,  0.00287495, -0.02567235,
          0.0142187 , -0.04707887, -0.03593844,  0.02596718],
        [-0.03688402,  0.02973201,  0.02412902, -0.01991005,
         -0.03255384,  0.04153048, -0.01581309,  0.04077045],
        [-0.03688402,  0.02973201,  0.02412902, -0.01991005,
         -0.03255384,  0.04153048, -0.01581309,  0.04077045],
        [-0.03688402,  0.02973201,  0.02412902, -0.01991005,
         -0.03255384,  0.04153048, -0.01581309,  0.04077045],
        [-0.03688402,  0.02973201,  0.02412902, -0.01991005,
         -0.03255384,  0.04153048, -0.01581309,  0.04077045],
        [-0.0368

In [81]:
padding_sequence[3]

array([51,  4, 40, 51, 96, 67, 27, 12,  0,  0], dtype=int32)